trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '18.x'

- task: Npm@1
  inputs:
    command: 'install'
  displayName: "Install NPM Dependencies"

- task: dependency-check-build-task@6
  inputs:
    projectName: '@shko.online/componentframework-mock'
    scanPath: 'package-lock.json'
    format: 'HTML, JSON, JUNIT'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'dependency-check/*junit.xml'
    searchFolder: '$(Common.TestResultsDirectory)'
    testRunTitle: 'Dependency Check'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'test'
  displayName: "Test"

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
  displayName: "Build"

- script: 'npx semantic-release'
  displayName: 'Semantic Release'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
    NPM_TOKEN: $(NPM_TOKEN)
  
- task: PublishCodeCoverageResults@1
  displayName: "Publish code coverage results"
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: "coverage/cobertura-coverage.xml"
